services:
  db:
    image: postgres:16.4
    container_name: smarttodo-db
    environment:
      POSTGRES_USER: smarttodo
      POSTGRES_PASSWORD: smarttodo
      POSTGRES_DB: smarttodo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smarttodo -d smarttodo"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: smarttodo-app
    read_only: true
    user: "1000:1000"
    env_file:
      - ./secrets-max.env
    volumes:
      - ./secrets-db:/etc/smarttodo/secrets-db:ro # секреты БД
    tmpfs:
      - /tmp
    ports:
      - "8080:8080"
    environment:
      - MAX_API_BASE_URL=https://platform-api.max.ru
      - MAX_API_TOKEN= #токен бота
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smarttodo
      - SPRING_DATASOURCE_USERNAME=smarttodo
      - SPRING_DATASOURCE_PASSWORD=smarttodo
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
